apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  labels:
    app: k8s-demo
    version: 1.0.0
    environment: production
spec:
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
        - name: k8s-demo
          image: justinjoram/nest-app:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000